# general
seed: 2020
state: INFO
reproducibility: True
checkpoint_dir: '/user/fsx/saved_path'
load_checkpoint_name: null
show_progress: True

log_wandb: False
wandb_project: 'HLLM'
MAX_ITEM_LIST_LENGTH: 10

data_path: /user/fsx/dataset/  # dataset path
dataset: Pixel8M  # dataset name

text_path: /user/fsx/information/  # Use absolute path
text_keys: ['title', 'tag', 'description']

loss: nce
neg_sample_mode: null
pad_random_sample: True

# training settings
epochs: 200
train_batch_size: 64  
optim_args: {
  learning_rate: 1e-3,
  weight_decay: 0.0
}
scheduler_args: {
  type: cosine,
  warmup: 0.1
}

# eval settings
category_by: 'item'
eval_batch_size: 1024
topk: [5,10,50,200]
metrics: ['Recall', 'NDCG']
shared_metrics: ['Entropy']
valid_metric: NDCG@10
metric_decimal_place: 7
eval_step: 1 
stopping_step: 10
metrics_pred_len_list: [1]  # eval_pred_len will be appended by default

strategy: deepspeed
precision: bf16-mixed
stage: 2
accumulate_grad: 1
